import Nav from '@/components/Nav'
import './globals.css'

export const metadata = {
  title: 'Blog - Evan Kagarise',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <Nav />
        {children}
        </body>
    </html>
  )
}
